"agile": agile
'agile.issue': Issue
'agile.release': Release
'agile.backlog': Backlog
'agile.scrumboard': Scrumboard
'agile.component': component
'agile.reporthost': Agile Report
'agile.reportboard': Report Workbench
'agile.projectsetting': Project Setting
'agile.fastsearch': Fast Search
'agile.issuelink': Issue Link
'agile.userStoryMap': Story Map
'agile.iterationBoard': Iteration Board
'agile.messageNotification': Notification Setting
'agile.feature': Feature
'agile.artCalendar': ART Calendar
'agile.pi': PI Objective
'agile.art': ART Setting
'agile.programBoard': Program Board

'agile.programSetting': Program Setting

"rentsetting": "Organization Settings"
"rentsetting.workCalendar": "Work Calendar"

"platform-reports": "Reports"
"platform-reports.reportboard": "Agile Report"
